CREATE TABLE IF NOT EXISTS `metricool_posts` (
    `id`                 INT AUTO_INCREMENT PRIMARY KEY,
    `action`             VARCHAR(50)   NOT NULL COMMENT 'post_general, post_twitter, youtube_video, etc.',
    `blog_id`            INT           NOT NULL COMMENT 'Metricool brand/blog ID',
    `row_number`         INT           DEFAULT NULL COMMENT 'Original row from source JSON',
    `slug`               VARCHAR(255)  DEFAULT NULL,
    `titulo`             VARCHAR(500)  DEFAULT NULL,
    `resumen`            TEXT          DEFAULT NULL,
    `contenido`          TEXT          DEFAULT NULL,
    `hashtags`           TEXT          DEFAULT NULL,
    `categoria`          VARCHAR(255)  DEFAULT NULL,
    `url_image`          TEXT          DEFAULT NULL,
    `promt_idea_image`   TEXT          DEFAULT NULL COMMENT 'AI prompt used to generate image',
    `fecha_registro`     VARCHAR(100)  DEFAULT NULL COMMENT 'Original date string from source',
    `status`             VARCHAR(50)   DEFAULT NULL COMMENT 'IMG-UP, etc.',
    `source_file`        VARCHAR(255)  DEFAULT NULL COMMENT 'JSON filename of origin',
    `fotos`              TEXT          DEFAULT NULL COMMENT 'JSON array of photo URLs sent',
    `platforms`          VARCHAR(100)  DEFAULT NULL COMMENT 'e.g. facebook,instagram,linkedin,gmb',
    `metricool_response` TEXT          DEFAULT NULL COMMENT 'Full Metricool API response JSON',
    `scheduled_date`     VARCHAR(50)   DEFAULT NULL COMMENT 'Date assigned by Metricool',
    `created_at`         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,

    INDEX `idx_action`      (`action`),
    INDEX `idx_blog_id`     (`blog_id`),
    INDEX `idx_slug`        (`slug`),
    INDEX `idx_categoria`   (`categoria`),
    INDEX `idx_source_file` (`source_file`),
    INDEX `idx_created_at`  (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
